# Generated by Django 6.0.1 on 2026-01-23 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = []
