# Generated by Django 6.0.1 on 2026-01-27 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_customuser_firebase_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='complaints/%Y/%m/%d/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='complaint',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='support_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='complaint',
            name='title',
            field=models.CharField(default='No Title', max_length=200),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['user', '-created_at'], name='app_complai_user_id_f92643_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['status', '-created_at'], name='app_complai_status_46e9e6_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['department', '-created_at'], name='app_complai_departm_06eaf4_idx'),
        ),
        migrations.AddField(
            model_name='complaintdocument',
            name='complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='app.complaint'),
        ),
    ]
