# Generated by Django 6.0.1 on 2026-02-04 09:27

import uuid
from django.db import migrations, models
from django.db.models import Q


def populate_tracking_ids(apps, schema_editor):
    Complaint = apps.get_model('app', 'Complaint')
    for complaint in Complaint.objects.filter(Q(tracking_id__isnull=True) | Q(tracking_id='')).iterator():
        complaint.tracking_id = str(uuid.uuid4())[:12].upper()
        complaint.save(update_fields=['tracking_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_civiccontact_verificationimage_volunteer_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_tracking_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='complaint',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
