# Generated by Django 6.0.1 on 2026-02-08 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_customuser_area_customuser_ward_customuser_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='area',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='ward',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='zone',
        ),
    ]
