# Generated by Codex on 2026-02-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_volunteer_area_remove_volunteer_ward_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='ward',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='zone',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='area',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
