# Generated by Django 6.0.2 on 2026-02-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_add_volunteer_location_fields_back'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='priority',
            field=models.CharField(default='NORMAL', max_length=10),
        ),
        migrations.AddField(
            model_name='complaint',
            name='sentiment',
            field=models.CharField(default='Neutral', max_length=20),
        ),
    ]
